#!/usr/bin/env sh

# Install pkg in new jails
env ASSUME_ALWAYS_YES=YES pkg bootstrap

# Install required packages
pkg updage -y
pkg install -y \
	git \
	python3 \
	py36-Flask \
	py36-Flask-Login \
	py36-wtforms \
	py36-Flask-wtf \
	py36-passlib \
	py36-pymysql \
	py36-gunicorn \

# Make to app directory
test -d /app || mkdir /app

# Clone the repo
git clone https://github.com/jwfh/librarian /app

# Copy the rc.d script into /etc/rc.d/
cp /app/etc/rc.d/librariand /etc/rc.d/librariand
chmod 555 /etc/rc.d/librariand

# Start the service at boot
echo 'librariand_enable="YES"' > /etc/rc.conf

# Make user to run the app as
pw useradd librariand -d /app